<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "relax5addinfo"
 *
 * Auto generated by Extension Builder 2017-05-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'relax5addinfo',
    'description' => 'Add additional info to any table in your database tables.',
    'category' => 'plugin',
    'author' => 'Christoph Balogh',
    'author_email' => 'cb@lustige-informatik.at',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '8.7.2-rc80322',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-8.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
